// 表设计器 DDL 构建：根据设计模型生成 CREATE TABLE，或对比新旧模型生成 ALTER 语句
//
// 模型结构（renderer 与 main 共享）：
// model = {
//   table, comment, options,                  // options: 建表附加子句（如 ClickHouse 引擎）
//   columns: [{ name, origName, type, length, scale, notNull, pk, autoInc, def, comment }],
//   indexes: [{ name, origName, columns:[..], unique }],
// }
// def 约定：'' 表示无默认值；其余按“原样/字面量”启发式处理（见 composeDefault）。

/** 各方言常用类型（供设计器下拉提示，允许自由输入） */
const TYPE_OPTIONS = {
  mysql: ['int', 'bigint', 'smallint', 'tinyint', 'decimal', 'float', 'double', 'varchar', 'char',
    'text', 'mediumtext', 'longtext', 'date', 'datetime', 'timestamp', 'time', 'year', 'json',
    'blob', 'longblob', 'enum', 'set', 'boolean'],
  postgres: ['integer', 'bigint', 'smallint', 'numeric', 'real', 'double precision', 'varchar',
    'char', 'text', 'boolean', 'date', 'timestamp', 'timestamptz', 'time', 'interval', 'json',
    'jsonb', 'uuid', 'bytea', 'inet'],
  mssql: ['int', 'bigint', 'smallint', 'tinyint', 'decimal', 'numeric', 'float', 'real', 'money',
    'varchar', 'nvarchar', 'char', 'nchar', 'text', 'ntext', 'bit', 'date', 'datetime',
    'datetime2', 'smalldatetime', 'time', 'uniqueidentifier', 'varbinary', 'image'],
  sqlite: ['INTEGER', 'TEXT', 'REAL', 'NUMERIC', 'BLOB'],
  clickhouse: ['UInt8', 'UInt16', 'UInt32', 'UInt64', 'Int8', 'Int16', 'Int32', 'Int64',
    'Float32', 'Float64', 'Decimal', 'String', 'FixedString', 'Date', 'Date32', 'DateTime',
    'DateTime64', 'Bool', 'UUID', 'Enum8', 'LowCardinality(String)'],
  oracle: ['NUMBER', 'VARCHAR2', 'NVARCHAR2', 'CHAR', 'NCHAR', 'DATE', 'TIMESTAMP', 'FLOAT',
    'CLOB', 'NCLOB', 'BLOB', 'RAW'],
};

/** 各方言能力（设计器据此显示/隐藏控件，构建时据此给告警） */
const CAPS = {
  mysql: { autoInc: true, comments: true, alterColumn: true, pkChange: true, indexes: true },
  postgres: { autoInc: true, comments: true, alterColumn: true, pkChange: true, indexes: true },
  mssql: { autoInc: true, comments: false, alterColumn: true, pkChange: true, indexes: true },
  sqlite: { autoInc: true, comments: false, alterColumn: false, pkChange: false, indexes: true },
  clickhouse: { autoInc: false, comments: true, alterColumn: true, pkChange: false, indexes: false },
  oracle: { autoInc: false, comments: true, alterColumn: true, pkChange: true, indexes: true },
};

function caps(dialect) { return CAPS[dialect] || CAPS.mysql; }
function typeOptions(dialect) { return TYPE_OPTIONS[dialect] || TYPE_OPTIONS.mysql; }

/** 组合完整类型串：varchar + 100 -> varchar(100)；decimal + 10,2 -> decimal(10,2) */
function composeType(col, dialect) {
  let t = String(col.type || '').trim();
  if (!t) t = dialect === 'sqlite' ? 'TEXT' : 'varchar';
  const len = String(col.length === undefined || col.length === null ? '' : col.length).trim();
  const scale = String(col.scale === undefined || col.scale === null ? '' : col.scale).trim();
  if (len && !/[()]/.test(t)) {
    t += scale ? `(${len},${scale})` : `(${len})`;
  }
  // ClickHouse 用 Nullable() 包装表达“可空”
  if (dialect === 'clickhouse' && !col.notNull && !/^(Nullable|Array|Map|Tuple|LowCardinality)\(/i.test(t)) {
    t = `Nullable(${t})`;
  }
  return t;
}

/** 默认值：数字/已知函数/带括号或 :: 的表达式原样输出，否则按字符串字面量 */
function composeDefault(adapter, def) {
  const s = String(def).trim();
  if (s === '') return null;
  if (/^-?\d+(\.\d+)?$/.test(s)) return s;
  if (/^(NULL|TRUE|FALSE)$/i.test(s)) return s.toUpperCase();
  if (/^(CURRENT_(TIMESTAMP|DATE|TIME)(\(\d*\))?|NOW\(\)|GETDATE\(\)|SYSDATETIME\(\)|SYSDATE|SYSTIMESTAMP|UUID\(\)|NEWID\(\)|GEN_RANDOM_UUID\(\))$/i.test(s)) return s;
  if (s.includes('(') || s.includes('::')) return s; // 表达式
  return adapter.literal(s);
}

/** 单列定义（CREATE / ADD / MODIFY 共用主体） */
function columnDef(adapter, dialect, col, opts = {}) {
  const q = (n) => adapter.quoteIdent(n);
  const parts = [q(col.name), composeType(col, dialect)];
  const d = composeDefault(adapter, col.def);

  if (dialect === 'clickhouse') {
    if (d !== null) parts.push('DEFAULT ' + d);
    if (col.comment) parts.push('COMMENT ' + adapter.literal(col.comment));
    return parts.join(' ');
  }
  if (dialect === 'oracle') {
    if (d !== null) parts.push('DEFAULT ' + d);
    if (col.notNull) parts.push('NOT NULL');
    return parts.join(' ');
  }
  // mysql / postgres / mssql / sqlite
  if (col.autoInc) {
    if (dialect === 'mysql') { parts.push('NOT NULL AUTO_INCREMENT'); return parts.join(' '); }
    if (dialect === 'mssql') parts.push('IDENTITY(1,1)');
    if (dialect === 'postgres') parts.push('GENERATED BY DEFAULT AS IDENTITY');
    if (dialect === 'sqlite' && opts.inlineSinglePk) {
      return `${q(col.name)} INTEGER PRIMARY KEY AUTOINCREMENT`;
    }
  }
  parts.push(col.notNull ? 'NOT NULL' : 'NULL');
  if (d !== null && !col.autoInc) parts.push('DEFAULT ' + d);
  if (dialect === 'mysql' && col.comment) parts.push('COMMENT ' + adapter.literal(col.comment));
  return parts.join(' ');
}

function indexName(ix, table) {
  return ix.name && ix.name.trim() ? ix.name.trim() : `idx_${table}_${ix.columns.join('_')}`.slice(0, 60);
}

/** CREATE TABLE（+ 索引 + 注释），返回 {sqls, warnings} */
function buildCreateTable(adapter, db, schema, model) {
  const dialect = adapter.dialect;
  const q = (n) => adapter.quoteIdent(n);
  const T = adapter.qualify(db, schema, model.table);
  const warnings = [];
  const cols = model.columns.filter((c) => c.name && c.name.trim());
  if (!cols.length) throw new Error('至少需要一个栏位');
  const pkCols = cols.filter((c) => c.pk).map((c) => c.name);

  const lines = [];
  const sqliteInlinePk = dialect === 'sqlite' && pkCols.length === 1 &&
    cols.find((c) => c.pk && c.autoInc && /int/i.test(c.type));
  for (const c of cols) {
    const inline = sqliteInlinePk && c.pk;
    lines.push('  ' + columnDef(adapter, dialect, c, { inlineSinglePk: inline }));
  }
  if (pkCols.length && !sqliteInlinePk && dialect !== 'clickhouse') {
    lines.push(`  PRIMARY KEY (${pkCols.map(q).join(', ')})`);
  }
  let sql = `CREATE TABLE ${T} (\n${lines.join(',\n')}\n)`;
  if (dialect === 'mysql') {
    sql += ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4';
    if (model.comment) sql += ' COMMENT ' + adapter.literal(model.comment);
  }
  if (dialect === 'clickhouse') {
    const opt = (model.options || '').trim() || 'ENGINE = MergeTree ORDER BY tuple()';
    sql += ' ' + opt;
    if (model.comment) sql += ` COMMENT ${adapter.literal(model.comment)}`;
    if (pkCols.length) warnings.push('ClickHouse 的主键由 ORDER BY 决定，请在表选项中设置（已忽略主键勾选）');
  }
  const sqls = [sql];

  // 索引
  if ((model.indexes || []).length) {
    if (!caps(dialect).indexes) {
      warnings.push('该数据库的索引不支持在设计器中创建，已忽略');
    } else {
      for (const ix of model.indexes) {
        if (!ix.columns || !ix.columns.length) continue;
        sqls.push(`CREATE ${ix.unique ? 'UNIQUE ' : ''}INDEX ${q(indexName(ix, model.table))} ON ${T} (${ix.columns.map(q).join(', ')})`);
      }
    }
  }
  // 注释（建表语句外补充）
  if (dialect === 'postgres' || dialect === 'oracle') {
    if (model.comment) sqls.push(`COMMENT ON TABLE ${T} IS ${adapter.literal(model.comment)}`);
    for (const c of cols) {
      if (c.comment) sqls.push(`COMMENT ON COLUMN ${T}.${q(c.name)} IS ${adapter.literal(c.comment)}`);
    }
  }
  if (dialect === 'mssql' && (model.comment || cols.some((c) => c.comment))) {
    warnings.push('SQL Server 的注释（扩展属性）暂不在设计器中生成');
  }
  return { sqls, warnings };
}

/** 对比新旧模型生成 ALTER 语句，返回 {sqls, warnings} */
function buildAlterTable(adapter, db, schema, original, model) {
  const dialect = adapter.dialect;
  const cap = caps(dialect);
  const q = (n) => adapter.quoteIdent(n);
  const T = adapter.qualify(db, schema, original.table);
  const sqls = [];
  const warnings = [];
  const L = (v) => adapter.literal(v);

  const origByName = new Map(original.columns.map((c) => [c.name, c]));
  const newCols = model.columns.filter((c) => c.name && c.name.trim());
  const keptOrig = new Set(newCols.filter((c) => c.origName).map((c) => c.origName));

  const fullType = (c) => composeType(c, dialect);
  const defStr = (c) => composeDefault(adapter, c.def);

  // 1) 重命名 + 修改
  for (const c of newCols) {
    if (!c.origName) continue;
    const o = origByName.get(c.origName);
    if (!o) continue;
    const renamed = c.name !== c.origName;
    const typeChanged = fullType(c) !== fullType(o);
    const nullChanged = !!c.notNull !== !!o.notNull;
    const defChanged = String(c.def || '') !== String(o.def || '');
    const cmtChanged = String(c.comment || '') !== String(o.comment || '');
    if (!renamed && !typeChanged && !nullChanged && !defChanged && !cmtChanged) continue;

    if (dialect === 'mysql') {
      // CHANGE 同时处理改名与定义
      sqls.push(`ALTER TABLE ${T} CHANGE COLUMN ${q(c.origName)} ${columnDef(adapter, dialect, c)}`);
      continue;
    }
    if (renamed) {
      if (dialect === 'mssql') {
        const full = `${schema || 'dbo'}.${original.table}.${c.origName}`;
        sqls.push(`EXEC sp_rename ${L(full)}, ${L(c.name)}, 'COLUMN'`);
      } else if (dialect === 'clickhouse') {
        sqls.push(`ALTER TABLE ${T} RENAME COLUMN ${q(c.origName)} TO ${q(c.name)}`);
      } else {
        sqls.push(`ALTER TABLE ${T} RENAME COLUMN ${q(c.origName)} TO ${q(c.name)}`);
      }
    }
    if (typeChanged || nullChanged || defChanged || cmtChanged) {
      if (dialect === 'sqlite') {
        warnings.push(`SQLite 不支持修改栏位 ${c.name} 的类型/约束（需重建表），相关改动已忽略`);
        continue;
      }
      if (dialect === 'postgres') {
        if (typeChanged) sqls.push(`ALTER TABLE ${T} ALTER COLUMN ${q(c.name)} TYPE ${fullType(c)}`);
        if (nullChanged) sqls.push(`ALTER TABLE ${T} ALTER COLUMN ${q(c.name)} ${c.notNull ? 'SET' : 'DROP'} NOT NULL`);
        if (defChanged) {
          const d = defStr(c);
          sqls.push(d === null
            ? `ALTER TABLE ${T} ALTER COLUMN ${q(c.name)} DROP DEFAULT`
            : `ALTER TABLE ${T} ALTER COLUMN ${q(c.name)} SET DEFAULT ${d}`);
        }
        if (cmtChanged) sqls.push(`COMMENT ON COLUMN ${T}.${q(c.name)} IS ${c.comment ? L(c.comment) : 'NULL'}`);
      } else if (dialect === 'mssql') {
        if (typeChanged || nullChanged) {
          sqls.push(`ALTER TABLE ${T} ALTER COLUMN ${q(c.name)} ${fullType(c)} ${c.notNull ? 'NOT NULL' : 'NULL'}`);
        }
        if (defChanged) {
          if (o.defConstraint) sqls.push(`ALTER TABLE ${T} DROP CONSTRAINT ${q(o.defConstraint)}`);
          const d = defStr(c);
          if (d !== null) sqls.push(`ALTER TABLE ${T} ADD CONSTRAINT ${q('DF_' + original.table + '_' + c.name)} DEFAULT ${d} FOR ${q(c.name)}`);
          else if (!o.defConstraint) warnings.push(`栏位 ${c.name} 的原默认值约束名未知，无法删除`);
        }
        if (cmtChanged) warnings.push(`SQL Server 注释修改暂不支持（栏位 ${c.name}）`);
      } else if (dialect === 'oracle') {
        const mods = [];
        if (typeChanged) mods.push(fullType(c));
        if (defChanged) { const d = defStr(c); mods.push('DEFAULT ' + (d === null ? 'NULL' : d)); }
        if (nullChanged) mods.push(c.notNull ? 'NOT NULL' : 'NULL');
        if (mods.length) sqls.push(`ALTER TABLE ${T} MODIFY (${q(c.name)} ${mods.join(' ')})`);
        if (cmtChanged) sqls.push(`COMMENT ON COLUMN ${T}.${q(c.name)} IS ${c.comment ? L(c.comment) : "''"}`);
      } else if (dialect === 'clickhouse') {
        if (typeChanged || defChanged) {
          let s = `ALTER TABLE ${T} MODIFY COLUMN ${q(c.name)} ${fullType(c)}`;
          const d = defStr(c);
          if (d !== null) s += ' DEFAULT ' + d;
          sqls.push(s);
        }
        if (cmtChanged) sqls.push(`ALTER TABLE ${T} COMMENT COLUMN ${q(c.name)} ${L(c.comment || '')}`);
      }
    }
  }

  // 2) 新增栏位
  for (const c of newCols) {
    if (c.origName) continue;
    if (dialect === 'oracle') {
      sqls.push(`ALTER TABLE ${T} ADD (${columnDef(adapter, dialect, c)})`);
      if (c.comment) sqls.push(`COMMENT ON COLUMN ${T}.${q(c.name)} IS ${L(c.comment)}`);
    } else if (dialect === 'postgres') {
      sqls.push(`ALTER TABLE ${T} ADD COLUMN ${columnDef(adapter, dialect, c)}`);
      if (c.comment) sqls.push(`COMMENT ON COLUMN ${T}.${q(c.name)} IS ${L(c.comment)}`);
    } else if (dialect === 'mssql') {
      sqls.push(`ALTER TABLE ${T} ADD ${columnDef(adapter, dialect, c)}`);
    } else {
      sqls.push(`ALTER TABLE ${T} ADD COLUMN ${columnDef(adapter, dialect, c)}`);
    }
    if (dialect === 'sqlite' && c.notNull && composeDefault(adapter, c.def) === null) {
      warnings.push(`SQLite 新增 NOT NULL 栏位 ${c.name} 需要提供默认值，否则会执行失败`);
    }
  }

  // 3) 删除栏位
  for (const o of original.columns) {
    if (keptOrig.has(o.name)) continue;
    if (newCols.some((c) => c.origName === o.name)) continue;
    sqls.push(`ALTER TABLE ${T} DROP COLUMN ${q(o.name)}`);
  }

  // 4) 主键变化
  const origPk = original.columns.filter((c) => c.pk).map((c) => c.name);
  const newPkOrigNames = newCols.filter((c) => c.pk).map((c) => c.origName || c.name);
  const newPk = newCols.filter((c) => c.pk).map((c) => c.name);
  if (JSON.stringify(origPk) !== JSON.stringify(newPkOrigNames)) {
    if (!cap.pkChange) {
      warnings.push('该数据库不支持在设计器中修改主键，相关改动已忽略');
    } else if (dialect === 'mysql') {
      if (origPk.length) sqls.push(`ALTER TABLE ${T} DROP PRIMARY KEY`);
      if (newPk.length) sqls.push(`ALTER TABLE ${T} ADD PRIMARY KEY (${newPk.map(q).join(', ')})`);
    } else {
      const pkIx = (original._pkIndexes || []).find((i) => i.name) || (original.indexes || []).find((i) => i.primary);
      const pkName = pkIx && pkIx.name;
      if (origPk.length) {
        if (pkName) sqls.push(`ALTER TABLE ${T} DROP CONSTRAINT ${q(pkName)}`);
        else warnings.push('未能确定原主键约束名，请手动删除原主键');
      }
      if (newPk.length) sqls.push(`ALTER TABLE ${T} ADD PRIMARY KEY (${newPk.map(q).join(', ')})`);
    }
  }

  // 5) 索引变化（按名称对比；忽略主键索引）
  if (cap.indexes) {
    const origIx = new Map((original.indexes || []).filter((i) => !i.primary).map((i) => [i.name, i]));
    const newIxs = (model.indexes || []).filter((i) => i.columns && i.columns.length);
    const seen = new Set();
    for (const ix of newIxs) {
      const name = indexName(ix, original.table);
      const o = ix.origName ? origIx.get(ix.origName) : null;
      if (o) {
        seen.add(ix.origName);
        const changed = name !== ix.origName ||
          JSON.stringify(o.columns) !== JSON.stringify(ix.columns) || !!o.unique !== !!ix.unique;
        if (!changed) continue;
        sqls.push(dropIndexSql(adapter, dialect, T, ix.origName));
        sqls.push(createIndexSql(adapter, dialect, T, { ...ix, name }));
      } else {
        sqls.push(createIndexSql(adapter, dialect, T, { ...ix, name }));
      }
    }
    for (const [name] of origIx) {
      if (!seen.has(name) && !newIxs.some((i) => i.origName === name)) {
        sqls.push(dropIndexSql(adapter, dialect, T, name));
      }
    }
  }

  // 6) 表注释
  if (String(model.comment || '') !== String(original.comment || '')) {
    if (dialect === 'mysql') sqls.push(`ALTER TABLE ${T} COMMENT = ${L(model.comment || '')}`);
    else if (dialect === 'postgres' || dialect === 'oracle') sqls.push(`COMMENT ON TABLE ${T} IS ${model.comment ? L(model.comment) : (dialect === 'oracle' ? "''" : 'NULL')}`);
    else if (dialect === 'clickhouse') sqls.push(`ALTER TABLE ${T} MODIFY COMMENT ${L(model.comment || '')}`);
    else warnings.push('该数据库的表注释修改暂不支持');
  }

  // 7) 表重命名（最后执行，避免影响前面的语句）
  if (model.table && model.table !== original.table) {
    sqls.push(adapter.renameSql(db, schema, original.table, model.table));
  }

  return { sqls, warnings };
}

function createIndexSql(adapter, dialect, T, ix) {
  const q = (n) => adapter.quoteIdent(n);
  return `CREATE ${ix.unique ? 'UNIQUE ' : ''}INDEX ${q(ix.name)} ON ${T} (${ix.columns.map(q).join(', ')})`;
}

function dropIndexSql(adapter, dialect, T, name) {
  const q = (n) => adapter.quoteIdent(n);
  if (dialect === 'mysql') return `ALTER TABLE ${T} DROP INDEX ${q(name)}`;
  if (dialect === 'mssql') return `DROP INDEX ${q(name)} ON ${T}`;
  return `DROP INDEX ${q(name)}`; // postgres / sqlite / oracle
}

/** 把 tableInfo 结果转换为设计器模型 */
function infoToModel(info, table, dialect) {
  const parseType = (full) => {
    const m = /^([^()]+?)\s*\(\s*([\d]+|max)\s*(?:,\s*(\d+))?\s*\)\s*$/i.exec(String(full || '').trim());
    if (m) return { type: m[1].trim(), length: m[2], scale: m[3] || '' };
    return { type: String(full || '').trim(), length: '', scale: '' };
  };
  const columns = info.columns.map((c) => {
    let full = c.type || '';
    let notNull = !c.nullable;
    if (dialect === 'clickhouse') {
      const nm = /^Nullable\((.+)\)$/i.exec(full);
      if (nm) { full = nm[1]; notNull = false; } else notNull = true;
    }
    const t = parseType(full);
    let def = c.def === null || c.def === undefined ? '' : String(c.def);
    return {
      name: c.name,
      origName: c.name,
      type: t.type,
      length: t.length,
      scale: t.scale,
      notNull,
      pk: c.key === 'PRI',
      autoInc: /auto_increment|identity/i.test(c.extra || ''),
      def,
      comment: c.comment || '',
      defConstraint: c.defConstraint || null,
    };
  });
  const indexes = (info.indexes || [])
    .filter((i) => !i.primary && i.name !== 'PRIMARY')
    .map((i) => ({
      name: i.name,
      origName: i.name,
      columns: (i.columns || []).slice(),
      unique: !!i.unique,
      primary: false,
    }));
  const pkIdx = (info.indexes || []).filter((i) => i.primary || i.name === 'PRIMARY');
  return {
    table,
    comment: info.tableComment || '',
    options: '',
    columns,
    indexes,
    // 保留主键索引信息供 ALTER 时取约束名
    _pkIndexes: pkIdx,
  };
}

module.exports = { typeOptions, caps, buildCreateTable, buildAlterTable, infoToModel, composeType, composeDefault };
